### ISSUE TITLE
Fluttter support or Webview URL

### ISSUE THREAD

**Issue by aTeamSolace** [paypal/ios-sdk#3]
Currently, there is no support for Flutter SDK. So I hope you will make it ASAP. Or if possible please share URL which we flutter developers render as web views. This is somewhat hard to get a web view URL of PayPal soo please share.

**Comment by scannillo** [comment]
Please see this note in our README.

> This repository is currently in development. The PayPal iOS SDK is not meant for public use. The repo is public for pilot merchants only.

I would reach out to PayPal support to express your concerns for whichever SDK you are indeed using (https://developer.paypal.com/support/). This SDK has no current plans to support Flutter.
