### ISSUE TITLE
public use? 

### ISSUE THREAD

**Issue by wbaumgar** [paypal/ios-sdk#6]
Hi, I stumbled across this framework when looking for an alternative for Paypal/PayPal-iOS-SDK. One of my requirements is that I need to be able to specify Payee email, which in this SDK looks like its possible. Will this framework be public anytime soon, since the only other native Paypal checkout is depreciated?

**Comment by scannillo** [comment]
Hi @wbaumgar - we don't have a timeline for when this framework will be publicly available. There are some backend components still in development that are halted at the moment. 

For now, you could take a look to see if the [Braintree SDKs](https://developers.braintreepayments.com/guides/client-sdk/setup/ios/v4)(which support PayPal checkouts) better suit your needs.

**Comment by wbaumgar** [comment]
Unfortunately this won't fit for my needs. The Braintree SDK depreciated allowing to specify the Payee email. This is a crucial feature I need for my app to work.

**Comment by scannillo** [comment]
@wbaumgar - unfortunately, this PayPal iOS SDK isn't ready for public use. Feel free to watch this GitHub repository to track it's first release.

**Comment by thirtified** [comment]
@wbaumgar Specifying a recipient for a PayPal transaction is a feature available to PayPal partners and does not necessarily require using this SDK. You may want to check out and apply for [PayPal's Partner Program](https://www.paypal.com/webapps/mpp/partner-programme). Have a look at [PayPal's Orders API](https://developer.paypal.com/docs/api/orders/v2/#definition-payee) how to specify a recipient (payee).
